logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: llol
    root_packages: com.app.llol
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false